# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000 # 500000 for 6h_vs_8z

runner: "episode"
batch_size_run: 1 # batch_size_run=4, buffer_size = 2500, batch_size=64  for 3s5z_vs_3s6z
buffer_size: 5000 
batch_size: 128
optimizer: 'adam'

t_max: 10050000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "n_mac"
agent: "n_rnn"

#agent: "rnn"

agent_output_type: q

learner: "q_learner"
mixer: "qmix"

#mixer: "qmix_135"


double_q: True
mixing_embed_dim: 32
hypernet_embed: 64
lr: 0.001 # Learning rate for agents
td_lambda: 0.6 # 0.3 for 6h_vs_8z
q_lambda: False

name: "qmix_save"

#save_model: True
#save_model_interval: 1000000


#expert
#medium
data_quality: "medium"
if_collect_data : True
#checkpoint_path: "/data/zpq/code_135/ResQ_src/results/models/5m_vs_6m/qmix_env=8_adam_td_lambda__2023-12-27_19-56-56"

#checkpoint_path: "/data/zpq/code_135/ResQ_src/results/models/3c9s15z/qmix_offline__2023-12-30_21-03-16"

#checkpoint_path: "/data/zpq/code_135/ResQ_src/results/models/8m_vs_9m/qmix_offline__2023-12-29_15-53-58"

#checkpoint_path: "/data/zpq/code_135/ResQ_src/results/models/27m_vs_30m/qmix_offline__2023-12-29_15-52-12"

#checkpoint_path: "/data/zpq/code_135/ResQ_src/results/models/45m_vs_50m/qmix_offline__2023-12-30_21-04-04"

#checkpoint_path: "/data/zpq/code_135/ResQ_src/results/models/MMM3/qmix_offline__2023-12-30_21-06-01"

#checkpoint_path: "/data/zpq/code_135/ResQ_src/results/models/MMM4/qmix_offline__2024-01-02_15-25-24"


checkpoint_path: "/data/zpq/code_135/pymarl/results/models/qmix__2024-01-05_10-27-48"

max_trajectories: 2000

obs_last_action: False #这个是100m_vs_100m地图要设置为False， 其它地图则设置为True就可以顺利加载模型了
hypernet_layers: 2 #这个是100m_vs_100m地图要设置为2， 其余地图则设置为1。因为保存100m_vs_100m地图的模型是采用2跑出来的，而其余地图之前保存模型是直接采用变量1保存下来的。

