# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000

runner: "episode"
batch_size_run: 1
buffer_size: 5000
batch_size: 128

# update the target network every {} episodes
target_update_interval: 200
t_max: 1010000

# use the Q_Learner to train
agent_output_type: "q"
learner: "restq_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

noopt_loss: 0.1
qmix_loss: 1

td_lambda: 0.6
lr: 0.001
resq_version: "v2"

name: "rest_qmix_v2_010"